#import "common.typ": *
// Findings section. Numbers come from `m` (results/expected/<model>.json); quoted answers are fixed model outputs.
== Findings

*1. Equal averages hide unequal knowledge.* Accuracy per language lies within a few points (Table 1, overlapping confidence intervals), so an aggregate benchmark would report Apertus as "equally good" in all four languages. At the level of individual facts this is false: #pct(m.cross_lingual.any_at_4) of facts are answered correctly in *at least one* language, but only #pct(m.cross_lingual.consistency_at_4) in *all four*; #m.cross_lingual.known_somewhere_but_not_everywhere facts are known somewhere but not everywhere (Fig. 2). Pairwise label agreement between languages is only #pct(calc.min(..m.cross_lingual.pairwise_agreement.values()))–#pct(calc.max(..m.cross_lingual.pairwise_agreement.values())). Example: the 100 000 signatures for an initiative on total revision (Art. 138) are known in German, while French and Italian answer "80 000" and Romansh "100 000 votantas e 60 000 votants".

*2. The model almost never abstains.* Only #m.overall.not_attempted of #m.overall.n answers are "not attempted"; when Apertus answers, it is wrong in #pct(m.overall.hallucination_rate) of cases. For a civic-information use case, calibrated abstention would be worth more than a confident wrong number.

*3. False premises are accepted, and the inventions differ by language.* On false-premise items, accuracy is #pct(m.by_type.false_premise.de) (DE), #pct(m.by_type.false_premise.fr) (FR), #pct(m.by_type.false_premise.it) (IT) and #pct(m.by_type.false_premise.rm) (RM). Asked which crimes the Constitution punishes by death (Art. 10 prohibits the death penalty), Apertus answers correctly in German and Italian but in French lists "trahison, haute trahison et meurtre" and in Romansh "tradiment, espionadi …". A non-existent "Swiss constitutional court" is said to have annulled federal laws "à 13 reprises" (FR) and "13 leschas federalas" (RM), although Art. 190 makes federal statutes binding on the Federal Supreme Court. English is claimed to be an official language "since 2000" (DE, FR) or "since 1996" (IT, RM).

*4. Romansh is not the weakest language on average, but the least predictable.* Romansh accuracy is in line with the other languages, and Romansh shows the most abstentions (#m.by_language.rm.not_attempted). However, facts that are correct in three languages most often fail in German or Romansh, so Romansh users cannot rely on knowledge demonstrated in another language.

*5. Simple facts are robust, procedural detail is not.* Composition numbers (200 National Council members, 46 Council of States members, 7 Federal Councillors, 4-year terms, 100-day referendum period, 1 August) are correct in all four languages. Errors concentrate on thresholds and qualifiers: the eight cantons that can call a referendum, the six cantons with half a cantonal vote, the 8.5% ceiling on corporate tax and the cantons' 17% share are wrong in every language, while the SNB's two-thirds profit share is answered correctly *only* in Romansh. List answers are the weakest answer type (Table 2).

*6. Cross-lingual disagreement is a free hallucination detector.* Because every fact is asked in four languages, the answers can be compared with each other without knowing the gold answer. For the #m.cross_lingual_signal.n number and yes/no items, where answers can be compared deterministically, an answer that agrees with the answers in *all* other languages is correct in #pct(m.cross_lingual_signal.agree_all.p_correct) of cases (n = #m.cross_lingual_signal.agree_all.n), one that agrees with *none* in only #pct(m.cross_lingual_signal.agree_none.p_correct) (n = #m.cross_lingual_signal.agree_none.n). As a correctness predictor, cross-lingual agreement reaches AUROC #calc.round(m.cross_lingual_signal.auroc, digits: 2). For a multilingual deployment this is a cheap, reference-free safeguard: ask in a second national language and flag disagreement.
